### ISSUE TITLE
Solution for confusion in Spine Generic

### ISSUE THREAD

**Issue by sandrinebedard** [spine-generic/data-multi-subject#174]
# Description

It might be confusing to have `space-other` in some of the labels but not all of them, also considering that we applided reorientation and resampling, but some of them were already in the right space.

## Proposed solution

- [x] Move the data from the root directory in `sourcedata `folder
- [x] Copy `derivatives/data-preprocessed` to the root directory 
- [x] Remove `derivatives/data-preprocessed`
- [x] Update the naming to remove `space-other`:
    - [x] from the raw images 
    - [x] from `derivatives/data-preprocessed`
    - [x] from `labels_softseg`
    - [x] from `labels_softseg_bin`
- [x] Fix json to follow our [convention](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#json-sidecars):
    - [x] `labels_softseg_bin`
    - [x] `labels_softseg`
    - [x]  `label-SC_seg` in `labels`
    Remove this,
~~~
"SpatialReference": {
        "Resampling": "1x1x1",
        "Reorientation": "RPI"
~~~

For `labels` `label-SC_seg`  :

```json
{
    "SpatialReference": "orig",
    "GeneratedBy": [
{
            "Name": "sct_deepseg_sc",
            "Version": "SCT v6.2"
},
            {
              "Name": "Manual",
              "Author": "Sandrine Bedard",
               "Date": "2021-07-25 13:39:39",
            }
]
}
```
- [ ] Temporary: add `space-other` to the discs labels if they are in different space
- [x] Long term: run totalspineseg on preprocessed data and replace old discs labels
- [ ] Test if possible to resample labels
- [x] Keep DWI data in root and source data folder
- [ ] Update README, explain how to use source data & update script

## TODO

- Edit change log
- Make a release 
- Announce in neurostars and sct forum
- Update spinegeneric scripts
